# Generated by Django 4.1.7 on 2023-04-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_alter_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
