# Generated by Django 4.1.7 on 2023-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_rename_image_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
